"""
Alpha Factor Service - Manage and evaluate the real 452-factor alpha zoo.

The catalog is generated by ``scripts/import_alpha_zoo.py`` from the Vibe-Trading
factor modules (academic, alpha101, gtja191, qlib158) and stored in
``backend/data/alpha_factors.json``. Each factor carries its real metadata
(theme, formula, columns required, universe, frequency, decay horizon, warmup)
and a resolvable ``module`` with a working ``compute(panel)`` entrypoint.

Beyond browsing, the service can compute factor values on a live OHLCV panel and
advise on the best strategy for a given trade (see ``advise_for_trade``).
"""
from typing import Dict, Any, Optional, List
from datetime import datetime
from importlib import import_module
from pathlib import Path

import numpy as np
import structlog

logger = structlog.get_logger(__name__)

_BACKEND_ROOT = Path(__file__).resolve().parent.parent.parent
_CATALOG_PATH = _BACKEND_ROOT / "data" / "alpha_factors.json"

_DIFFICULTY_BY_WARMUP = [(60, "Advanced"), (20, "Intermediate"), (0, "Basic")]


def _difficulty(warmup: Optional[int]) -> str:
    if not warmup:
        return "Basic"
    for threshold, label in sorted(_DIFFICULTY_BY_WARMUP, reverse=True):
        if warmup >= threshold:
            return label
    return "Basic"


def _theme_to_category(theme: Optional[list]) -> str:
    if not theme:
        return "Quantitative"
    cat_map = {
        "momentum": "Momentum",
        "reversal": "Mean-Reversion",
        "reversion": "Mean-Reversion",
        "mean-reversion": "Mean-Reversion",
        "volatility": "Volatility",
        "volume": "Volume",
        "liquidity": "Liquidity",
        "value": "Value",
        "growth": "Growth",
        "trend": "Trend",
        "quality": "Quality",
        "size": "Size",
        "cross-sectional": "Cross-Sectional",
        "seasonality": "Seasonality",
        "sentiment": "Sentiment",
        "carry": "Carry",
        "statistical": "Statistical",
        "technical": "Technical",
    }
    for key in theme:
        if isinstance(key, str) and key.lower() in cat_map:
            return cat_map[key.lower()]
    return str(theme[0]).replace("-", " ").title() if theme else "Quantitative"


class AlphaFactorService:
    """
    Alpha Factor Service - Manage, evaluate, and trade alongside 452 alpha factors.

    Features:
    - Browse the real 452-factor zoo (catalog JSON)
    - Compute factor values on a live OHLCV panel
    - Advise on the best factor-driven strategy for a pending trade
    - Get factor performance metrics
    - Add factors to backtest strategy
    """

    def __init__(self, db: AsyncSession = None):
        self.db = db
        self.alpha_factors = self._load_alpha_factors()

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    def _load_alpha_factors(self) -> List[Dict[str, Any]]:
        """Load the real catalog from backend/data/alpha_factors.json."""
        try:
            import json

            with open(_CATALOG_PATH, encoding="utf-8") as fh:
                raw = json.load(fh)
        except Exception as exc:  # noqa: BLE001
            logger.warning("alpha factor catalog unavailable", error=str(exc))
            return []

        factors = []
        for i, entry in enumerate(raw, start=1):
            warmup = entry.get("min_warmup_bars")
            factors.append(
                {
                    "id": entry.get("id", f"f-{i}"),
                    "name": entry.get("nickname")
                    or entry.get("id")
                    or f"Factor {i}",
                    "category": _theme_to_category(entry.get("theme")),
                    "difficulty": _difficulty(warmup),
                    "description": entry.get("notes")
                    or entry.get("formula_latex")
                    or entry.get("id", ""),
                    "formulas": entry.get("formula_latex", ""),
                    "zoo": entry.get("zoo", ""),
                    "theme": entry.get("theme", []),
                    "columns_required": entry.get("columns_required", []),
                    "universe": entry.get("universe", []),
                    "frequency": entry.get("frequency", []),
                    "decay_horizon": entry.get("decay_horizon"),
                    "min_warmup_bars": warmup,
                    "module": entry.get("module", ""),
                    "has_compute": bool(entry.get("has_compute")),
                    # Performance metrics are computed on demand (see
                    # get_factor_performance); static fields kept for API parity.
                    "win_rate": None,
                    "sharpe": None,
                    "max_drawdown": None,
                    "avg_return": None,
                    "copied_count": None,
                    "code_snippet": f"compute(panel) from {entry.get('module', '')}",
                }
            )
        return factors

    # ------------------------------------------------------------------
    # Browse
    # ------------------------------------------------------------------

    async def get_factors(
        self,
        category: Optional[str] = None,
        difficulty: Optional[str] = None,
        min_sharpe: Optional[float] = None,
        min_win_rate: Optional[float] = None,
        search_query: Optional[str] = None,
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        """Get factors with filters."""
        factors = self.alpha_factors.copy()

        if category:
            factors = [f for f in factors if f["category"].lower() == category.lower()]

        if difficulty:
            factors = [f for f in factors if f["difficulty"].lower() == difficulty.lower()]

        if min_sharpe:
            factors = [f for f in factors if (f.get("sharpe") or 0) >= min_sharpe]

        if min_win_rate:
            factors = [f for f in factors if (f.get("win_rate") or 0) >= min_win_rate]

        if search_query:
            query = search_query.lower()
            factors = [
                f
                for f in factors
                if query in f["name"].lower()
                or query in f["description"].lower()
                or query in f["id"].lower()
            ]

        return factors[:limit]

    async def get_factor_by_id(self, factor_id: str) -> Optional[Dict[str, Any]]:
        for factor in self.alpha_factors:
            if factor["id"] == factor_id:
                return factor
        return None

    async def get_categories(self) -> List[str]:
        return sorted({f["category"] for f in self.alpha_factors})

    # ------------------------------------------------------------------
    # Strategy / backtest
    # ------------------------------------------------------------------

    async def add_factor_to_strategy(
        self,
        factor_id: str,
        strategy_name: str,
        weight: float = 1.0,
    ) -> Dict[str, Any]:
        factor = await self.get_factor_by_id(factor_id)
        if not factor:
            return {"error": "Factor not found"}

        logger.info(
            f"Added factor {factor_id} to strategy {strategy_name}",
            weight=weight,
            zoo=factor.get("zoo"),
        )
        return {
            "status": "success",
            "factor_id": factor_id,
            "factor_name": factor["name"],
            "zoo": factor.get("zoo"),
            "theme": factor.get("theme"),
            "strategy_name": strategy_name,
            "weight": weight,
        }

    async def get_factor_performance(
        self,
        factor_id: str,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
    ) -> Optional[Dict[str, Any]]:
        factor = await self.get_factor_by_id(factor_id)
        if not factor:
            return None

        return {
            "factor_id": factor_id,
            "factor_name": factor["name"],
            "zoo": factor.get("zoo"),
            "theme": factor.get("theme"),
            "universe": factor.get("universe"),
            "columns_required": factor.get("columns_required"),
            "min_warmup_bars": factor.get("min_warmup_bars"),
            "decay_horizon": factor.get("decay_horizon"),
            "formula": factor.get("formulas"),
            "period": "live",
            "total_return": None,
            "sharpe_ratio": None,
            "max_drawdown": None,
            "win_rate": None,
            "avg_monthly_return": None,
            "notes": "Benchmark metrics are computed per-symbol via /alpha-factors/{id}/evaluate.",
        }

    async def get_ensemble_performance(
        self,
        factor_ids: List[str],
        strategy_name: str = "Custom Ensemble",
    ) -> Dict[str, Any]:
        factors = []
        for fid in factor_ids:
            factor = await self.get_factor_by_id(fid)
            if factor:
                factors.append(factor)

        if not factors:
            return {"error": "No valid factors found"}

        return {
            "strategy_name": strategy_name,
            "factor_count": len(factors),
            "factors": [f["name"] for f in factors],
            "zoos": sorted({f.get("zoo", "") for f in factors}),
            "themes": sorted({t for f in factors for t in f.get("theme", [])}),
            "estimated_sharpe": None,
            "estimated_win_rate": None,
            "estimated_drawdown": None,
            "estimated_annual_return": None,
            "diversification_benefit": None,
            "notes": "Ensemble metrics require a live evaluation pass (see /evaluate).",
        }

    # ------------------------------------------------------------------
    # Computation on live data
    # ------------------------------------------------------------------

    def get_compute_module(self, factor_id: str) -> Optional[Any]:
        """Resolve the factor's compute(panel) entrypoint, if available."""
        factor = next((f for f in self.alpha_factors if f["id"] == factor_id), None)
        if not factor or not factor.get("module"):
            return None
        try:
            return import_module(factor["module"])
        except Exception as exc:  # noqa: BLE001
            logger.warning("factor module import failed", factor=factor_id, error=str(exc))
            return None

    async def compute_factor(
        self,
        factor_id: str,
        panel: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Compute a single factor on an OHLCV panel.

        ``panel`` must be a dict of wide DataFrames keyed by column (close,
        open, high, low, volume, ...). Each DataFrame has a DatetimeIndex and
        instrument columns. Returns the factor's latest scores plus metadata.
        """
        factor = await self.get_factor_by_id(factor_id)
        if not factor:
            return {"error": "Factor not found"}

        mod = self.get_compute_module(factor_id)
        if mod is None or not callable(getattr(mod, "compute", None)):
            return {"error": f"Factor {factor_id} has no runnable compute"}

        missing = [c for c in factor.get("columns_required", []) if c not in panel]
        if missing:
            return {
                "error": f"Missing required columns for {factor_id}: {', '.join(missing)}",
                "columns_required": factor.get("columns_required"),
                "columns_available": sorted(panel.keys()),
            }

        try:
            values = mod.compute(panel)
        except Exception as exc:  # noqa: BLE001
            logger.warning("factor compute failed", factor=factor_id, error=str(exc))
            return {"error": f"Factor compute failed: {exc}"}

        latest = {}
        try:
            if isinstance(values, dict):
                latest = values
            else:
                for col in values.columns:
                    series = values[col].dropna()
                    if len(series):
                        latest[col] = float(series.iloc[-1])
        except Exception as exc:  # noqa: BLE001
            logger.warning("factor result shaping failed", factor=factor_id, error=str(exc))

        return {
            "factor_id": factor_id,
            "factor_name": factor["name"],
            "zoo": factor.get("zoo"),
            "theme": factor.get("theme"),
            "formula": factor.get("formulas"),
            "values": latest,
            "warmup_required": factor.get("min_warmup_bars"),
        }

    async def advise_for_trade(
        self,
        symbol: str,
        panel: Dict[str, Any],
        side: str = "buy",
        limit_to_zoos: Optional[List[str]] = None,
        top: int = 10,
        universe: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Advise on the best factor-driven strategy for a pending trade.

        Runs every computable factor against the provided OHLCV panel, keeps the
        factors whose columns are satisfied and whose last value is non-NaN,
        scores each by |z-score| (signal strength), and groups the winners by
        theme to recommend a strategy (momentum / mean-reversion / volatility /
        trend, ...). The recommended direction is the consensus sign.

        Because real compute() functions are used, this drives execution
        strategy selection hand-in-hand with actual market conditions.
        """
        side = (side or "buy").lower()
        results = []
        candidates = self.alpha_factors
        if limit_to_zoos:
            candidates = [f for f in candidates if f.get("zoo") in limit_to_zoos]

        for factor in candidates:
            if not factor.get("has_compute"):
                continue
            if universe and factor.get("universe") and universe not in factor["universe"]:
                continue
            missing = [c for c in factor.get("columns_required", []) if c not in panel]
            if missing:
                continue

            mod = self.get_compute_module(factor["id"])
            if mod is None or not callable(getattr(mod, "compute", None)):
                continue

            try:
                values = mod.compute(panel)
                score = None
                series = None
                if isinstance(values, dict):
                    series = values.get(symbol)
                else:
                    if symbol in getattr(values, "columns", []):
                        series = values[symbol].dropna()
                    elif len(getattr(values, "columns", [])) == 1:
                        series = values[values.columns[0]].dropna()
                if series is None:
                    continue
                s = list(series)
                if len(s) < 2:
                    continue
                last = float(s[-1])
                if last != last:  # NaN guard
                    continue
                mean = float(np.mean(s))
                std = float(np.std(s)) or 1.0
                zscore = (last - mean) / std
                score = last
            except Exception:  # noqa: BLE001
                continue

            results.append(
                {
                    "factor_id": factor["id"],
                    "name": factor["name"],
                    "zoo": factor.get("zoo"),
                    "theme": factor.get("theme", []),
                    "category": factor["category"],
                    "score": score,
                    "zscore": zscore,
                    "abs_score": abs(zscore),
                    "signal": 1 if zscore > 0 else (-1 if zscore < 0 else 0),
                    "columns_required": factor.get("columns_required"),
                    "decay_horizon": factor.get("decay_horizon"),
                }
            )

        # Rank by |z-score| (scale-free), normalize to a 0-1 confidence.
        if not results:
            return {
                "symbol": symbol,
                "side": side,
                "computable": 0,
                "total_candidates": len(candidates),
                "recommendation": None,
                "strategy": None,
                "factors": [],
            }

        results.sort(key=lambda r: r["abs_score"], reverse=True)
        max_score = max(1.0, max(r["abs_score"] for r in results))
        for r in results:
            r["confidence"] = round(min(1.0, r["abs_score"] / max_score), 3)

        top_results = results[:top]
        sig_pos = sum(1 for r in top_results if r["signal"] > 0)
        sig_neg = sum(1 for r in top_results if r["signal"] < 0)
        consensus = 1 if sig_pos > sig_neg else (-1 if sig_neg > sig_pos else 0)
        recommended_direction = {1: "long", -1: "short", 0: "neutral"}[consensus]

        # Theme-level strategy recommendation.
        theme_counts: Dict[str, int] = {}
        for r in top_results:
            for t in r["theme"]:
                theme_counts[t] = theme_counts.get(t, 0) + 1
        dominant_theme = max(theme_counts, key=theme_counts.get) if theme_counts else "mixed"

        strategy = {
            "momentum": "Momentum continuation: trend-following entries aligned with consensus signal.",
            "reversal": "Mean-reversion: counter-trend entries on extreme factor readings.",
            "volatility": "Volatility regime: size exposure to realized/implied vol compression.",
            "trend": "Trend: follow the dominant moving-average / linear-drift direction.",
            "volume": "Volume/microstructure: confirm signal with accumulation/distribution.",
            "value": "Value: size to relative cheapness vs fundamentals.",
            "sentiment": "Sentiment: trade the news/social flow momentum.",
            "statistical": "Statistical: exploit autocorrelation/entropy regime.",
        }
        strategy_desc = strategy.get(dominant_theme, "Mixed-factor: composite of top-ranked signals.")

        return {
            "symbol": symbol,
            "side": side,
            "computable": len(results),
            "total_candidates": len(candidates),
            "consensus_signal": consensus,
            "recommended_direction": recommended_direction,
            "matches_side": (side in ("buy", "long") and consensus > 0) or (side in ("sell", "short") and consensus < 0),
            "strategy": {
                "theme": dominant_theme,
                "description": strategy_desc,
                "confidence": round(sum(r["confidence"] for r in top_results) / max(1, len(top_results)), 3),
                "net_signal": round(sum(r["signal"] for r in top_results) / max(1, len(top_results)), 3),
            },
            "factors": top_results,
        }