"""
Embedded OpenWA Service
Runs OpenWA (WhatsApp API) as a subprocess within the backend.

This eliminates the need for a separate OpenWA hosting.
OpenWA starts automatically when backend starts, stops when backend stops.

Requirements:
- Node.js 16+ installed
- @open-wa/wa-automate package

Setup:
1. Install Node.js from https://nodejs.org/
2. npm install @open-wa/wa-automate in backend directory
3. Service auto-starts on backend startup
"""
import subprocess
import asyncio
import structlog
import os
from pathlib import Path
from typing import Optional, Dict, Any
import json
import httpx

logger = structlog.get_logger(__name__)


class EmbeddedOpenWA:
    """
    Embedded OpenWA Service - WhatsApp API as subprocess.
    
    Manages OpenWA lifecycle:
    - Starts on backend startup
    - Runs on port 3001 (configurable)
    - Auto-restarts on crash
    - Graceful shutdown on backend stop
    """
    
    def __init__(self):
        self.process: Optional[subprocess.Popen] = None
        self.port = 3001
        self.host = "localhost"
        self.is_running = False
        self.server_url = f"http://{self.host}:{self.port}"
        self.config_file = Path("data/openwa_config.json")
        self._qr_code: Optional[str] = None
        self._session_active = False
        
    def _get_script_path(self) -> Path:
        """Get path to OpenWA server script."""
        # Try multiple locations
        possible_paths = [
            Path(__file__).parent.parent / "openwa_server.js",
            Path(__file__).parent.parent.parent / "openwa_server.js",
            Path.cwd() / "openwa_server.js",
        ]
        
        for path in possible_paths:
            if path.exists():
                return path
        
        # Create default script if not found
        return self._create_default_script()
    
    def _create_default_script(self) -> Path:
        """Create default OpenWA server script."""
        script_path = Path(__file__).parent.parent / "openwa_server.js"
        
        script_content = """// OpenWA Server Script
// Auto-generated by Jasper Trades backend
const waAutomate = require('@open-wa/wa-automate');

const PORT = process.env.OPENWA_PORT || 3001;
const HOST = process.env.OPENWA_HOST || 'localhost';

let client = null;
let qrCode = null;
let sessionActive = false;

async function start() {
    console.log('Starting OpenWA server...');
    
    try {
        // Create WhatsApp client
        client = await waAutomate.create({
            sessionId: 'jasper-trades',
            headless: true,
            authTimeout: 60000,
            cacheEnabled: false,
            useChrome: false,
            browserArgs: ['--no-sandbox', '--disable-setuid-sandbox'],
            qrTimeout: 60000,
            autoRefresh: true,
        });
        
        // Register message handler
        client.onMessage(async (message) => {
            console.log('Message received:', message.from, message.body);
            
            // Forward to backend webhook
            try {
                await fetch('http://localhost:8000/whatsapp/webhook', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        phone: message.from,
                        message: message.body,
                        timestamp: new Date().toISOString(),
                    }),
                });
            } catch (error) {
                console.error('Failed to forward message:', error);
            }
        });
        
        sessionActive = true;
        console.log('OpenWA server started successfully on port', PORT);
        
    } catch (error) {
        console.error('Failed to start OpenWA:', error);
        process.exit(1);
    }
}

// HTTP server for health checks and QR code
const http = require('http');

const server = http.createServer((req, res) => {
    const url = new URL(req.url, `http://${HOST}:${PORT}`);
    
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Access-Control-Allow-Origin', '*');
    
    if (url.pathname === '/health') {
        res.writeHead(200);
        res.end(JSON.stringify({
            status: 'ok',
            sessionActive: sessionActive,
            hasQrCode: qrCode !== null,
        }));
    } else if (url.pathname === '/qr') {
        res.writeHead(200);
        res.end(JSON.stringify({
            qrCode: qrCode,
            sessionActive: sessionActive,
        }));
    } else if (url.pathname === '/send') {
        if (req.method !== 'POST') {
            res.writeHead(405);
            res.end(JSON.stringify({ error: 'Method not allowed' }));
            return;
        }
        
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', async () => {
            try {
                const data = JSON.parse(body);
                const { phone, message } = data;
                
                if (!client || !sessionActive) {
                    res.writeHead(503);
                    res.end(JSON.stringify({ error: 'WhatsApp session not active' }));
                    return;
                }
                
                // Send message
                await client.sendText(phone, message);
                
                res.writeHead(200);
                res.end(JSON.stringify({ success: true }));
            } catch (error) {
                console.error('Send error:', error);
                res.writeHead(500);
                res.end(JSON.stringify({ error: error.message }));
            }
        });
        return;
    } else {
        res.writeHead(404);
        res.end(JSON.stringify({ error: 'Not found' }));
        return;
    }
});

server.listen(PORT, HOST, () => {
    console.log(`OpenWA HTTP server listening on ${HOST}:${PORT}`);
    start();
});

// Handle graceful shutdown
process.on('SIGINT', () => {
    console.log('Shutting down OpenWA...');
    if (client) {
        client.kill();
    }
    server.close(() => {
        process.exit(0);
    });
});
"""
        
        script_path.parent.mkdir(exist_ok=True)
        with open(script_path, 'w') as f:
            f.write(script_content)
        
        logger.info(f"Created default OpenWA server script at {script_path}")
        return script_path
    
    def _check_node_installed(self) -> bool:
        """Check if Node.js is installed."""
        try:
            result = subprocess.run(
                ["node", "--version"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            return result.returncode == 0
        except (subprocess.SubprocessError, FileNotFoundError):
            return False
    
    def _check_openwa_installed(self) -> bool:
        """Check if @open-wa/wa-automate is installed."""
        try:
            # Check if package exists in node_modules
            node_modules = Path.cwd() / "node_modules" / "@open-wa" / "wa-automate"
            return node_modules.exists()
        except Exception:
            return False
    
    async def start(self) -> bool:
        """
        Start OpenWA as subprocess.

        Returns:
            True if started successfully, False otherwise
        """
        if self.is_running:
            logger.warning("OpenWA already running")
            return True
        
        # Check prerequisites
        if not self._check_node_installed():
            logger.error("Node.js not installed. Install from https://nodejs.org/")
            return False
        
        if not self._check_openwa_installed():
            logger.warning("@open-wa/wa-automate not installed. Run: npm install @open-wa/wa-automate")
            # Continue anyway - script may fail gracefully
        
        script_path = self._get_script_path()
        
        try:
            logger.info(f"Starting OpenWA from {script_path}")
            
            # Build environment variables
            env = os.environ.copy()
            env["OPENWA_PORT"] = str(self.port)
            env["OPENWA_HOST"] = self.host
            
            self.process = subprocess.Popen(
                ["node", str(script_path)],
                cwd=str(Path.cwd()),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                env=env,
            )
            
            self.is_running = True
            
            # Wait for startup (monitor stdout)
            await asyncio.sleep(3)
            
            # Check if process is still running
            if self.process.poll() is not None:
                stdout, stderr = self.process.communicate()
                logger.error(f"OpenWA failed to start: {stderr.decode()}")
                self.is_running = False
                return False
            
            logger.info(f"OpenWA started on port {self.port}")
            
            # Load config
            self._load_config()
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to start OpenWA: {e}")
            self.is_running = False
            return False
    
    async def stop(self):
        """Stop OpenWA subprocess."""
        if not self.is_running or not self.process:
            return
        
        logger.info("Stopping OpenWA...")
        
        try:
            # Graceful shutdown
            self.process.terminate()
            
            # Wait up to 5 seconds
            try:
                self.process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                # Force kill
                self.process.kill()
            
            self.is_running = False
            self._session_active = False
            
            logger.info("OpenWA stopped")
            
        except Exception as e:
            logger.error(f"Error stopping OpenWA: {e}")
    
    def _load_config(self):
        """Load OpenWA config from file."""
        if self.config_file.exists():
            try:
                with open(self.config_file, 'r') as f:
                    config = json.load(f)
                    self.port = config.get("port", 3001)
                    self.host = config.get("host", "localhost")
                    self.server_url = f"http://{self.host}:{self.port}"
            except Exception as e:
                logger.debug(f"Failed to load OpenWA config: {e}")
    
    def _save_config(self):
        """Save OpenWA config to file."""
        self.config_file.parent.mkdir(exist_ok=True)
        config = {
            "port": self.port,
            "host": self.host,
        }
        with open(self.config_file, 'w') as f:
            json.dump(config, f, indent=2)
    
    async def get_health(self) -> Dict[str, Any]:
        """Get OpenWA health status."""
        if not self.is_running:
            return {"status": "not_running", "sessionActive": False}
        
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                response = await client.get(f"{self.server_url}/health")
                if response.status_code == 200:
                    return response.json()
        except Exception as e:
            logger.debug(f"Health check failed: {e}")
        
        return {"status": "unreachable", "sessionActive": False}
    
    async def get_qr_code(self) -> Optional[str]:
        """Get QR code for WhatsApp linking."""
        if not self.is_running:
            return None
        
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                response = await client.get(f"{self.server_url}/qr")
                if response.status_code == 200:
                    data = response.json()
                    return data.get("qrCode")
        except Exception as e:
            logger.debug(f"QR fetch failed: {e}")
        
        return None
    
    async def send_message(self, phone: str, message: str) -> bool:
        """Send WhatsApp message via OpenWA."""
        if not self.is_running:
            logger.warning("OpenWA not running, cannot send message")
            return False
        
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.post(
                    f"{self.server_url}/send",
                    json={"phone": phone, "message": message},
                )
                
                if response.status_code == 200:
                    data = response.json()
                    return data.get("success", False)
                else:
                    logger.error(f"OpenWA send failed: {response.status_code}")
                    return False
                    
        except Exception as e:
            logger.error(f"OpenWA send error: {e}")
            return False
    
    def configure(self, port: int = 3001, host: str = "localhost"):
        """Configure OpenWA settings."""
        self.port = port
        self.host = host
        self.server_url = f"http://{host}:{port}"
        self._save_config()
        logger.info(f"OpenWA configured: {host}:{port}")
    
    def get_status(self) -> Dict[str, Any]:
        """Get OpenWA status."""
        return {
            "is_running": self.is_running,
            "port": self.port,
            "host": self.host,
            "server_url": self.server_url,
            "session_active": self._session_active,
            "node_installed": self._check_node_installed(),
            "openwa_installed": self._check_openwa_installed(),
        }


# Singleton instance
embedded_openwa = EmbeddedOpenWA()


def get_embedded_openwa() -> EmbeddedOpenWA:
    """Get the embedded OpenWA service instance."""
    return embedded_openwa