
// OpenWA Server Script
// Auto-generated by Jasper Trades backend
const waAutomate = require('@open-wa/wa-automate');

const PORT = process.env.OPENWA_PORT || 3001;
const HOST = process.env.OPENWA_HOST || 'localhost';

let client = null;
let qrCode = null;
let sessionActive = false;

async function start() {
    console.log('Starting OpenWA server...');
    
    try {
        // Create WhatsApp client
        client = await waAutomate.create({
            sessionId: 'jasper-trades',
            headless: true,
            authTimeout: 60000,
            cacheEnabled: false,
            useChrome: false,
            browserArgs: ['--no-sandbox', '--disable-setuid-sandbox'],
            qrTimeout: 60000,
            autoRefresh: true,
        });
        
        // Register message handler
        client.onMessage(async (message) => {
            console.log('Message received:', message.from, message.body);
            
            // Forward to backend webhook
            try {
                await fetch('http://localhost:8000/whatsapp/webhook', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        phone: message.from,
                        message: message.body,
                        timestamp: new Date().toISOString(),
                    }),
                });
            } catch (error) {
                console.error('Failed to forward message:', error);
            }
        });
        
        sessionActive = true;
        console.log('OpenWA server started successfully on port', PORT);
        
    } catch (error) {
        console.error('Failed to start OpenWA:', error);
        process.exit(1);
    }
}

// HTTP server for health checks and QR code
const http = require('http');

const server = http.createServer((req, res) => {
    const url = new URL(req.url, `http://${HOST}:${PORT}`);
    
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Access-Control-Allow-Origin', '*');
    
    if (url.pathname === '/health') {
        res.writeHead(200);
        res.end(JSON.stringify({
            status: 'ok',
            sessionActive: sessionActive,
            hasQrCode: qrCode !== null,
        }));
    } else if (url.pathname === '/qr') {
        res.writeHead(200);
        res.end(JSON.stringify({
            qrCode: qrCode,
            sessionActive: sessionActive,
        }));
    } else if (url.pathname === '/send') {
        if (req.method !== 'POST') {
            res.writeHead(405);
            res.end(JSON.stringify({ error: 'Method not allowed' }));
            return;
        }
        
        let body = '';
        req.on('data', chunk => body += chunk);
        req.on('end', async () => {
            try {
                const data = JSON.parse(body);
                const { phone, message } = data;
                
                if (!client || !sessionActive) {
                    res.writeHead(503);
                    res.end(JSON.stringify({ error: 'WhatsApp session not active' }));
                    return;
                }
                
                // Send message
                await client.sendText(phone, message);
                
                res.writeHead(200);
                res.end(JSON.stringify({ success: true }));
            } catch (error) {
                console.error('Send error:', error);
                res.writeHead(500);
                res.end(JSON.stringify({ error: error.message }));
            }
        });
        return;
    } else {
        res.writeHead(404);
        res.end(JSON.stringify({ error: 'Not found' }));
        return;
    }
});

server.listen(PORT, HOST, () => {
    console.log(`OpenWA HTTP server listening on ${HOST}:${PORT}`);
    start();
});

// Handle graceful shutdown
process.on('SIGINT', () => {
    console.log('Shutting down OpenWA...');
    if (client) {
        client.kill();
    }
    server.close(() => {
        process.exit(0);
    });
});
